import type { Metadata } from 'next'
import { Manrope } from 'next/font/google'

import type { ReactNode } from 'react'
import { Header } from '@/widgets/Header'

import './globals.css'
import 'swiper/css'

const manrope = Manrope({ subsets: ['cyrillic'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <Header />
        <main>
          {children}
        </main>
      </body>
    </html>
  )
}
